Repository Morak-Team/Frontend, pull requests merged in 2025-04, with the labels that each got.

#2 [Feat] 카카오 로그인 로직을 구현한다.
  index.html
  package.json
  public/images/.gitkeep
  public/images/kakao_login_button.png
  src/apis/kakaoLogin/api.js
  src/apis/kakaoLogin/getKakaoData.js
  src/apis/kakaoLogin/postKakaoToken.js
  src/apis/kakaoLogin/queries.js
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/routes/router.jsx
  yarn.lock
Labels: Feat

#6 Init: Husky 적용
  .github/workflows/buildCheck.yaml
  .husky/pre-commit
  eslint.config.js
  package.json
  src/pages/home/Home.jsx
  vite.config.js
  yarn.lock
Labels: Chore

#7 Chore: 코드래빗 테스트
  src/pages/home/Home.jsx
Labels: Chore

#9 [Feat] PWA 기능 구현
  .github/.coderabbit/config.yaml
  package.json
  public/favicon.svg
  public/pwa-192x192.png
  public/pwa-512x512.png
  public/robots.txt
  vite.config.js
  yarn.lock
Labels: Feat

#10 [Feat] 네이버 지도 API 연결을 구현한다.
  jsconfig.json
  src/App.jsx
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/pages/map/MapPage.jsx
  src/pages/map/components/MapViewer.jsx
  src/pages/map/utils/loadMapScript.js
  src/routes/router.jsx
  vite.config.js
Labels: Feat

#16 Feat: 하단 탭 컴포넌트 구현
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  src/components/.gitkeep
  src/components/layout/BottomTab.jsx
  src/components/layout/LayoutWithTab.jsx
  src/routes/router.jsx
Labels: Feat

#18 Feat: 전체 리뷰 페이지 무한 스크롤 구현
  package.json
  src/App.jsx
  src/apis/.gitkeep
  src/apis/review/getReviews.js
  src/apis/review/queries.js
  src/hooks/.gitkeep
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/review/StoreReviewPage.jsx
  src/routes/router.jsx
  yarn.lock
Labels: Feat

#19 [Feat] 지도 검색 기능 구현 및 검색 결과 렌더링
  index.html
  public/images/sample1.jpeg
  public/images/sample2.jpeg
  public/images/sample2.png
  public/images/sample3.jpeg
  public/images/sample4.jpeg
  public/svgs/ic_Search.svg
  public/svgs/ic_arrow_left.svg
  src/App.jsx
  src/constants/map/socialEnterprise.js
  src/pages/map/MapPage.jsx
  src/pages/map/components/MapViewer.jsx
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/search/SearchPage.jsx
  src/pages/search/components/PlaceCard.jsx
  src/pages/search/components/RecentSearchList.jsx
  src/pages/search/components/SearchBar.jsx
  src/pages/search/components/SearchPlaceList.jsx
  src/routes/router.jsx
  src/styles/map.css
Labels: Feat, Design

#22 Feat: 스토리 페이지 뼈대 구현
  package.json
  src/main.jsx
  src/pages/error/ErrorPage.jsx
  src/pages/story/StoryPage.jsx
  src/pages/story/components/StoryDetail.jsx
  src/pages/story/components/carousel/BestStoryCarousel.jsx
  src/pages/story/components/carousel/CategoryCarousel.jsx
  src/pages/story/components/carousel/StoryCarousel.jsx
  src/pages/story/components/content/Category.jsx
  src/pages/story/components/content/SlideContent.jsx
  src/pages/story/components/content/StoryContent.jsx
  src/pages/story/utils/grabbing.js
  src/pages/support/SupportPage.jsx
  src/routes/router.jsx
  src/styles/global.css
  src/styles/swiper.css
  tailwind.config.js
  yarn.lock
Labels: Feat, Design

#26 Feat: 리뷰 작성용 카메라 및 갤러리 연동
  package.json
  src/apis/review/getPresignedUrl.js
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/ReviewImageCapture.jsx
  vite.config.js
  yarn.lock
Labels: Feat

#29 Feat: 리뷰 사진 촬영 후 선택, 페이지 이동 로직 구현
  src/apis/review/getPresignedUrl.js
  src/apis/review/getReviewList.js
  src/apis/review/postImageKey.js
  src/apis/review/postRecipt.js
  src/apis/review/uploadImageToS3.js
  src/pages/map/components/ConfirmImage.jsx
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/ReviewImageCapture.jsx
  src/pages/writeReview/WriteReviewPage.jsx
  src/routes/router.jsx
Labels: Feat

#30 [Feat] 지도에서 사용자 현재 위치 버튼 및 카테고리 바 기능 구현
  public/svgs/Ic_Cafe.svg
  public/svgs/Ic_Community.svg
  public/svgs/Ic_Restaurent.svg
  public/svgs/Ic_Shopping.svg
  public/svgs/ic_X_Btn.svg
  public/svgs/ic_location.svg
  src/components/layout/BottomTab.jsx
  src/constants/map/socialEnterprise.js
  src/pages/map/MapPage.jsx
  src/pages/map/components/CategoryBar.jsx
  src/pages/map/components/MapViewer.jsx
Labels: Feat, Design

#31 [ Design] 타이포 시스템 적용
  index.html
  public/images/Icon_Profile.png
  public/images/bottomTab/mapMenuIcon.png
  public/images/bottomTab/profileMenuIcon.png
  public/images/bottomTab/storyMenuIcon.png
  public/images/bottomTab/supportMenuIcon.png
  public/images/review/cameraIcon.png
  public/images/review/galleryIcon.png
  public/images/review/reciptIcon.png
  public/images/review/xButtonIcon.png
  public/images/review/xButtonIconForModal.png
  src/components/layout/BottomTab.jsx
  src/constants/.gitkeep
  src/constants/review/reviewData.js
  src/pages/map/MapPage.jsx
  src/pages/map/components/CategoryBar.jsx
  src/pages/map/components/Modal.jsx
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/map/components/ReviewContent.jsx
  src/pages/map/components/ReviewImageCapture.jsx
  src/pages/map/components/ReviewList.jsx
  src/pages/search/components/SearchBar.jsx
  src/pages/writeReview/WriteReviewPage.jsx
  src/pages/writeReview/components/Complete.jsx
  src/pages/writeReview/components/SelectTag.jsx
  src/pages/writeReview/components/WriteText.jsx
  src/styles/global.css
  tailwind.config.js
Labels: Style

#32 [Feat] 카카오 로그인 구현 및 회원가입 플로우 초기 세팅
  package.json
  public/images/img_illust.png
  public/images/kakao_login_button.png
  public/images/kakao_login_large_wide.png
  public/svgs/Ic_Profile.svg
  public/svgs/Ic_X_Btn.svg
  public/svgs/Ic_check.svg
  public/svgs/ic_heart.svg
  src/apis/kakaoLogin/getKakaoData.js
  src/apis/kakaoLogin/postKakaoToken.js
  src/components/layout/BottomTab.jsx
  src/pages/home/Home.jsx
  src/pages/join/SignUp.jsx
  src/pages/join/components/NameStep.jsx
  src/pages/join/components/ProfileImageStep.jsx
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/routes/router.jsx
  vite.config.js
  yarn.lock
Labels: Feat, Design

#34 [Design] 바텀 시트 내부 리뷰 뷰 구현
  public/images/bottomTab/mapMenuIcon.png
  public/images/bottomTab/profileMenuIcon.png
  public/images/bottomTab/storyMenuIcon.png
  public/images/bottomTab/supportMenuIcon.png
  public/svgs/bottomTab/mapMenuIcon.svg
  public/svgs/bottomTab/profileMenuIcon.svg
  public/svgs/bottomTab/storyMenuIcon.svg
  public/svgs/bottomTab/supportMenuIcon.svg
  public/svgs/ic_X_Btn.svg
  public/svgs/review/pinIcon.svg
  public/svgs/review/profileIcon.svg
  public/svgs/review/tags/meaningful.svg
  public/svgs/review/writeReviewIcon.svg
  public/svgs/review/xIcon.svg
  src/apis/review/getReviews.js
  src/components/layout/BottomTab.jsx
  src/constants/review/tagList.js
  src/hooks/useDragScroll.js
  src/pages/join/components/NameStep.jsx
  src/pages/map/components/ConfirmImage.jsx
  src/pages/map/components/Modal.jsx
  src/pages/map/components/ReviewContent.jsx
  src/pages/map/components/ReviewImageCapture.jsx
  src/pages/map/components/ReviewList.jsx
  src/pages/writeReview/components/SelectTag.jsx
  tailwind.config.js
Labels: Design

#38 [Design] 사진 검증/리뷰 작성 플로우 전체적인 퍼블리싱 완료
  public/images/review/cameraIcon.png
  public/images/review/galleryIcon.png
  public/images/review/reciptIcon.png
  public/images/review/xButtonIcon.png
  public/images/review/xButtonIconForModal.png
  public/svgs/ic_X.svg
  public/svgs/ic_arrow_left.svg
  public/svgs/ic_heart_fill.svg
  public/svgs/review/camera/cameraIcon.svg
  public/svgs/review/camera/galleryIcon.svg
  public/svgs/review/camera/receiptIcon.svg
  public/svgs/review/camera/xButtonIcon.svg
  public/svgs/review/camera/xButtonIconForModal.svg
  public/svgs/review/fire.svg
  public/svgs/review/fireIcon.svg
  public/svgs/review/temperLogo.svg
  public/svgs/review/uploadReview.svg
  public/svgs/review/warningIcon copy.svg
  public/svgs/review/warningIcon.svg
  src/apis/review/getReviewDetail.js
  src/apis/review/postRecipt.js
  src/components/layout/BottomTab.jsx
  src/pages/map/components/ConfirmImage.jsx
  src/pages/map/components/DatePickerSheet.jsx
  src/pages/map/components/Modal.jsx
  src/pages/map/components/Picker.jsx
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/ReceiptErrorModal.jsx
  src/pages/map/components/ReviewContent.jsx
  src/pages/map/components/ReviewImageCapture.jsx
  src/pages/map/components/ReviewList.jsx
  src/pages/map/components/TimePickerSheet.jsx
  src/pages/writeReview/WriteReviewPage.jsx
  src/pages/writeReview/components/Complete.jsx
  src/pages/writeReview/components/SelectTag.jsx
  src/pages/writeReview/components/UploadingModal.jsx
  src/pages/writeReview/components/WriteText.jsx
  src/store/uiStore.js
Labels: Feat, Design

#39 [Feat] 회원가입 지역 및 역할 선택 단계 구현 및 API 연동
  public/images/Img_Background.png
  public/images/Img_Join.svg
  public/images/Img_Start_Morak.png
  public/images/img_illust.png
  public/svgs/Ic_Check_orange.svg
  public/svgs/Ic_Heart_Empty.svg
  public/svgs/Ic_Heart_empty.svg
  public/svgs/Ic_Profile.svg
  src/apis/kakaoLogin/api.js
  src/apis/kakaoLogin/postKakaoToken.js
  src/apis/kakaoLogin/queries.js
  src/apis/member/signup.js
  src/assets/svgs/signup/Ic_Check_Circle.svg
  src/assets/svgs/signup/Ic_Check_Orange.svg
  src/assets/svgs/signup/Ic_Unselected.svg
  src/assets/svgs/signup/Img_Profile_Blue.svg
  src/assets/svgs/signup/Img_Profile_Gray.svg
  src/assets/svgs/signup/Img_Profile_Orange.svg
  src/assets/svgs/signup/Img_Profile_Pink.svg
  src/assets/svgs/signup/index.js
  src/pages/join/SignUp.jsx
  src/pages/join/components/GoHome.jsx
  src/pages/join/components/LocationStep.jsx
  src/pages/join/components/NameStep.jsx
  src/pages/join/components/OwnerStep.jsx
  src/pages/join/components/ProfileImageStep.jsx
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/styles/global.css
  vite.config.js
Labels: Feat, Design
