Repository Morak-Team/Frontend, pull requests merged in 2025-05, with the labels that each got.

#45 [Refactor] 지도 페이지 기능 수정 및 성능 개선
  public/svgs/Ic_Heart_Empty.svg
  public/svgs/Ic_X.svg
  src/apis/kakaoLogin/postKakaoToken.js
  src/pages/home/Home.jsx
  src/pages/join/components/GoHome.jsx
  src/pages/join/components/LocationStep.jsx
  src/pages/join/components/NameStep.jsx
  src/pages/join/components/OwnerStep.jsx
  src/pages/join/components/ProfileImageStep.jsx
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/pages/map/MapPage.jsx
  src/pages/map/components/CategoryBar.jsx
  src/pages/map/components/ConfirmImage.jsx
  src/pages/map/components/DatePickerSheet.jsx
  src/pages/map/components/IntroModal.jsx
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/map/components/ReviewContent.jsx
  src/pages/map/components/ReviewList.jsx
  src/pages/map/components/TimePickerSheet.jsx
  src/pages/map/hooks/useMapViewer.js
  src/pages/map/hooks/useToggleLike.js
  src/pages/review/components/Reviews.jsx
  src/pages/search/SearchPage.jsx
  src/pages/search/components/PlaceCard.jsx
  src/pages/search/components/SearchPlaceList.jsx
  src/pages/search/hooks/useCompanyData.js
  src/pages/search/hooks/useUserCoords.js
  src/pages/writeReview/components/Complete.jsx
  src/pages/writeReview/components/SelectTag.jsx
  src/pages/writeReview/components/WriteText.jsx
  src/store/authStore.js
Labels: Refactor, Design

#48 [Feat] 지원 공고 및 금융 상품 추천 기능 구현 완성
  public/svgs/Ic_Heart_Empty.svg
  public/svgs/support/company/checkIcon.svg
  public/svgs/support/company/checkbox.svg
  public/svgs/support/company/linkIcon.svg
  public/svgs/support/company/thumb.svg
  src/apis/announcement/getAnnouncement.js
  src/apis/announcement/getFOADetail.js
  src/apis/announcement/queries.js
  src/apis/instance/api.js
  src/apis/recommend/postUserInfo.js
  src/pages/support/SupportItemPage.jsx
  src/pages/support/SupportListPage.jsx
  src/pages/support/SupportPage.jsx
  src/pages/support/SupportRecommendPage.jsx
  src/pages/support/components/CompanyTab.jsx
  src/pages/support/components/FOACard.jsx
  src/pages/support/components/FOAItem.jsx
  src/pages/support/components/step/Step1.jsx
  src/pages/support/components/step/Step2.jsx
  src/pages/support/components/step/Step3.jsx
  src/pages/support/components/step/Step4.jsx
  src/pages/support/components/step/Step5.jsx
  src/pages/support/components/step/Step6.jsx
  src/pages/support/components/step/Step7.jsx
  src/routes/router.jsx
  src/styles/spinner.css
Labels: Feat

#51 [Desgin] 베스트 스토리 캐러셀 및 디테일 페이지 기능 구현
  public/images/1.jpeg
  public/images/2.jpeg
  public/pwa-192x192.png
  public/pwa-512x512.png
  public/svgs/story/backIcon.svg
  public/svgs/story/moveIcon.svg
  public/svgs/story/storyFireIcon.svg
  public/svgs/story/whiteFireIcon.svg
  src/apis/member/auth.js
  src/apis/member/queries.js
  src/apis/story/getBestStory.js
  src/apis/story/getBestStoryDetail.js
  src/apis/story/patchStoryLike.js
  src/apis/story/queries.js
  src/components/layout/BottomTab.jsx
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/map/components/ReviewList.jsx
  src/pages/review/StoreReviewPage.jsx
  src/pages/review/components/PlaceInfo.jsx
  src/pages/story/StoryPage.jsx
  src/pages/story/components/StoryDetail.jsx
  src/pages/story/components/carousel/BestStoryCarousel.jsx
  src/pages/story/components/content/SlideContent.jsx
  src/routes/router.jsx
  src/store/uiStore.js
  src/styles/swiper.css
Labels: Design

#56 [Feat] 이야기 페이지 최근 올라온 스토리 섹션 구현
  src/apis/story/getRecentStories.js
  src/apis/story/queries.js
  src/pages/story/StoryPage.jsx
  src/pages/story/components/StoryDetail.jsx
  src/pages/story/components/carousel/StoryCarousel.jsx
  src/pages/story/components/content/SlideContent.jsx
Labels: Feat, Design

#59 [Feat] 지원페이지 소비자 탭 소비 가치 통계 및 금융상품 추천 컴포넌트 구현
  package.json
  public/svgs/Ic_All.svg
  public/svgs/Ic_Heart_Empty.svg
  public/svgs/support/consumer/Ic_speechBubble.svg
  public/svgs/support/consumer/Img_FinancialProduct.svg
  src/apis/consumer/getConsumptionDetail.js
  src/components/common/HaveToLoginModal.jsx
  src/components/common/Spinner.jsx
  src/constants/categoryMap.js
  src/pages/map/components/ReviewList.jsx
  src/pages/review/components/PlaceInfo.jsx
  src/pages/review/components/Reviews.jsx
  src/pages/story/components/StoryDetail.jsx
  src/pages/support/FinancialProductDetailPage.jsx
  src/pages/support/FinancialProductListPage.jsx
  src/pages/support/SupportPage.jsx
  src/pages/support/components/ConsumerTab.jsx
  src/pages/support/components/ConsumptionChart.jsx
  src/pages/support/components/CustomTooltip.jsx
  src/pages/support/components/RecommendationCard.jsx
  src/pages/support/constants/consumerMap.js
  src/pages/support/hooks/useConsumptionData.js
  src/pages/support/hooks/useFinancialProductDetail.js
  src/pages/support/hooks/useFinancialProducts.js
  src/routes/router.jsx
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: Feat

#62 [Feat] 마이페이지 기능 구현 완료
  public/svgs/myPage/edit.svg
  public/svgs/signUp/kakao.svg
  public/svgs/signUp/signUp.svg
  src/apis/member/getCheerCountOfMember.js
  src/apis/member/getLikeCountOfMember.js
  src/apis/member/getReviewCountOfMember.js
  src/apis/member/queries.js
  src/components/common/HaveToLoginModal.jsx
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/pages/myPage/MyPage.jsx
Labels: Feat

#63 [Feat] 지도 페이지 실시간 현위치 반영 기능 구현 및 UI 수정
  public/svgs/Ic_Heart-Empty.svg
  src/pages/map/MapPage.jsx
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/map/hooks/useMapViewer.js
  src/pages/search/SearchPage.jsx
  src/pages/search/components/PlaceCard.jsx
  src/pages/story/components/carousel/StoryCarousel.jsx
Labels: Feat, Design

#67 [Fix] 지도 페이지 초기 중심 좌표 및 실시간 위치 추적 개선
  public/svgs/map/Ic_Link.svg
  src/pages/map/MapPage.jsx
  src/pages/map/components/CategoryBar.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/map/hooks/useMapViewer.js
  src/pages/map/utils/openNaverMapRoute.js
  src/pages/review/components/PlaceInfo.jsx
  src/routes/router.jsx
Labels: Feat

#71 [Fix] 지도 페이지 QA 반영
  public/svgs/categoryBar/Ic_All.svg
  src/components/common/ToastModal.jsx
  src/constants/categoryMap.js
  src/pages/map/MapPage.jsx
  src/pages/map/components/CategoryBar.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/map/hooks/useToggleLike.js
  src/pages/review/components/PlaceInfo.jsx
  src/store/authStore.js
  tailwind.config.js
Labels: Fix, Refactor

#73 [Fix] 지도페이지 검색 결과 및 찜 기능 오류 수정
  src/pages/join/components/LocationStep.jsx
  src/pages/join/components/NameStep.jsx
  src/pages/join/components/OwnerStep.jsx
  src/pages/join/components/ProfileImageStep.jsx
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/map/hooks/useToggleLike.js
  src/pages/search/SearchPage.jsx
  src/pages/search/components/MapViewer.jsx
  src/pages/search/hooks/useMapViewer.js
Labels: Fix

#66 [Feat] 소비자 소비 유형 기반 맞춤 금융상품 추천 필터링 로직 구현
  public/svgs/support/consumer/Ic_Alert.svg
  public/svgs/support/consumer/Ic_SupportMessage.svg
  src/pages/join/components/GoHome.jsx
  src/pages/join/components/LocationStep.jsx
  src/pages/join/components/NameStep.jsx
  src/pages/join/components/OwnerStep.jsx
  src/pages/join/components/ProfileImageStep.jsx
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/pages/map/MapPage.jsx
  src/pages/map/components/CategoryBar.jsx
  src/pages/map/components/IntroModal.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/search/SearchPage.jsx
  src/pages/search/components/PlaceCard.jsx
  src/pages/search/components/SearchPlaceList.jsx
  src/pages/story/components/carousel/StoryCarousel.jsx
  src/pages/support/FinancialProductDetailPage.jsx
  src/pages/support/FinancialProductListPage.jsx
  src/pages/support/SupportPage.jsx
  src/pages/support/components/ConsumerTab.jsx
  src/pages/support/components/ConsumptionChart.jsx
  src/pages/support/components/HaveToLoginModal.jsx
  src/pages/support/components/RecommendationCard.jsx
  src/pages/support/constants/consumerMap.js
  tailwind.config.js
Labels: Feat, Design

#75 Feat: 마이페이지 회원이 작성한 리뷰/응원한 스토리 확인 기능
  public/images/1.jpeg
  public/images/2.jpeg
  public/images/kakao_login_large_wide.png
  public/images/sample1.jpeg
  public/images/sample2.jpeg
  public/images/sample3.jpeg
  public/images/sample4.jpeg
  public/svgs/myPage/backIcon.svg
  public/svgs/myPage/cheer.svg
  public/svgs/myPage/heart.svg
  public/svgs/myPage/noResult.svg
  public/svgs/myPage/review.svg
  src/apis/myPage/getDetail.js
  src/apis/myPage/queries.js
  src/apis/review/getPresignedUrl.js
  src/apis/review/likeToggle.js
  src/apis/review/postImageKey.js
  src/apis/review/postRecipt.js
  src/apis/review/postReview.js
  src/apis/review/uploadImageToS3.js
  src/components/common/HaveToLoginModal.jsx
  src/components/layout/BottomTab.jsx
  src/components/layout/LayoutWithTab.jsx
  src/constants/iconMap.js
  src/constants/map/socialEnterprise.js
  src/pages/error/ErrorPage.jsx
  src/pages/map/components/picker/DatePickerSheet.jsx
  src/pages/map/components/picker/Picker.jsx
  src/pages/map/components/picker/TimePickerSheet.jsx
  src/pages/map/components/review/ReviewContent.jsx
  src/pages/map/components/review/ReviewList.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPageDetail/MyPageDetailPage.jsx
  src/pages/myPageDetail/components/ReviewItem.jsx
  src/pages/myPageDetail/components/StoryItem.jsx
  src/pages/review/StoreReviewPage.jsx
  src/pages/review/components/PlaceInfo.jsx
  src/pages/story/StoryPage.jsx
  src/pages/story/components/StoryDetail.jsx
  src/pages/story/components/carousel/BestStoryCarousel.jsx
  src/pages/story/components/carousel/StoryCarousel.jsx
  src/pages/story/components/content/SlideContent.jsx
  src/pages/story/utils/grabbing.js
  src/pages/support/SupportItemPage.jsx
  src/pages/support/SupportListPage.jsx
  src/pages/support/SupportPage.jsx
  src/pages/support/components/CompanyTab.jsx
  src/pages/support/components/FOACard.jsx
  src/pages/support/components/FOAItem.jsx
  src/pages/support/components/step/Step6.jsx
  src/pages/support/utils/dateFunc.js
  src/routes/router.jsx
  src/store/useLikeStore.js
  src/store/userInfoStore.js
  src/styles/spinner.css
Labels: Feat

#76 [Feat] 리뷰/응원한 스토리 없을 때 보이는 페이지 구현
  src/pages/myPageDetail/MyPageDetailPage.jsx
Labels: Feat, Design

#74 [Fix] 지도 페이지 및 전체적인 QA 반영
  public/svgs/common/Ic_All.svg
  public/svgs/common/Ic_Arrow_Left.svg
  public/svgs/common/Ic_Heart-Empty.svg
  public/svgs/common/Ic_Heart_Fill.svg
  public/svgs/common/Ic_X.svg
  public/svgs/common/Ic_X_Btn.svg
  public/svgs/common/favicon.svg
  src/pages/join/SignUp.jsx
  src/pages/join/components/GoHome.jsx
  src/pages/join/components/LocationStep.jsx
  src/pages/join/components/NameStep.jsx
  src/pages/join/components/OwnerStep.jsx
  src/pages/join/components/ProfileImageStep.jsx
  src/pages/kakaoAuth/kakaoAuth.jsx
  src/pages/map/MapPage.jsx
  src/pages/map/components/IntroModal.jsx
  src/pages/map/components/PlaceBottomSheet.jsx
  src/pages/map/components/PlaceContent.jsx
  src/pages/map/hooks/useToggleLike.js
  src/pages/search/SearchPage.jsx
  src/pages/search/components/RecentSearchList.jsx
  src/pages/search/components/SearchBar.jsx
  src/pages/search/hooks/useMapViewer.js
  src/pages/support/components/ConsumerTab.jsx
  src/store/authStore.js
Labels: Fix, Refactor

#77 [Fix] 지원 공고 페이지 주관기관 표기 및 코드 중복 해소
  src/hooks/useLikeToggle.js
  src/pages/map/components/review/ReviewContent.jsx
  src/pages/myPageDetail/MyPageDetailPage.jsx
  src/pages/myPageDetail/components/ReviewItem.jsx
  src/pages/review/components/PlaceInfo.jsx
  src/pages/review/components/Reviews.jsx
  src/pages/support/FinancialProductDetailPage.jsx
  src/pages/support/FinancialProductListPage.jsx
  src/pages/support/SupportItemPage.jsx
  src/pages/support/SupportListPage.jsx
  src/pages/support/SupportRecommendPage.jsx
  src/pages/support/components/FOACard.jsx
  src/pages/support/components/FOAItem.jsx
  src/pages/support/utils/dateFunc.js
  src/pages/writeReview/components/Complete.jsx
  src/pages/writeReview/components/WriteText.jsx
Labels: Refactor

#79 [Feat] 마이페이지 찜목록 및 프로필 편집 기능 구현
  src/apis/member/postUpdateProfile.js
  src/apis/member/queries.js
  src/apis/myPage/getDetail.js
  src/apis/myPage/queries.js
  src/assets/svgs/modal/Ic_Warn.svg
  src/assets/svgs/modal/index.js
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/components/.gitkeep
  src/pages/myPage/components/MyPageEdit.jsx
  src/pages/myPageDetail/MyPageDetailPage.jsx
  src/pages/myPageDetail/components/HeartItem.jsx
  src/pages/myPageDetail/components/MapCompanyPage.jsx
  src/pages/story/components/StoryDetail.jsx
  src/routes/router.jsx
Labels: Feat, Design

#82 Docs: 리드미 수정 (이미지 안뜸, 양식 수정 등)
  README.md
Labels: Docs
